//
// Generated file, do not edit! Created by nedtool 5.0 from Messages/SM_CloudProvider_Control.msg.
//

#ifndef __SM_CLOUDPROVIDER_CONTROL_M_H
#define __SM_CLOUDPROVIDER_CONTROL_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "SIMCAN_Message.h"
// }}

/**
 * Class generated from <tt>Messages/SM_CloudProvider_Control.msg:9</tt> by nedtool.
 * <pre>
 * ///
 * /// SIMCAN Message for User requests
 * ///
 * message SM_CloudProvider_Control extends SIMCAN_Message
 * {
 *     @customize(false);
 * 
 *     string messageText;		// ID of the user instance
 * }
 * </pre>
 */
class SM_CloudProvider_Control : public ::SIMCAN_Message
{
  protected:
    omnetpp::opp_string messageText;

  private:
    void copy(const SM_CloudProvider_Control& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SM_CloudProvider_Control&);

  public:
    SM_CloudProvider_Control(const char *name=nullptr, int kind=0);
    SM_CloudProvider_Control(const SM_CloudProvider_Control& other);
    virtual ~SM_CloudProvider_Control();
    SM_CloudProvider_Control& operator=(const SM_CloudProvider_Control& other);
    virtual SM_CloudProvider_Control *dup() const {return new SM_CloudProvider_Control(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getMessageText() const;
    virtual void setMessageText(const char * messageText);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SM_CloudProvider_Control& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SM_CloudProvider_Control& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SM_CLOUDPROVIDER_CONTROL_M_H

