//
// Generated file, do not edit! Created by nedtool 5.0 from Messages/SM_UserAPP_Finish.msg.
//

#ifndef __SM_USERAPP_FINISH_M_H
#define __SM_USERAPP_FINISH_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
	#include "SIMCAN_Message.h"
	
// }}

/**
 * Class generated from <tt>Messages/SM_UserAPP_Finish.msg:11</tt> by nedtool.
 * <pre>
 * ///
 * /// SIMCAN Message for User requests
 * ///
 * message SM_UserAPP_Finish extends SIMCAN_Message
 * {
 *     @customize(false);
 * 
 *     string userID;		// ID of the user instance
 *     string strVmId;	    // Id of the VM that allocs the APP
 *     string strApp;		// Name of the application
 *     int nTotalTime;		// Execution time of the application	
 *     //int nExecStatus;	// Execution status (idle, running, finished, timeout)
 * }
 * </pre>
 */
class SM_UserAPP_Finish : public ::SIMCAN_Message
{
  protected:
    omnetpp::opp_string userID;
    omnetpp::opp_string strVmId;
    omnetpp::opp_string strApp;
    int nTotalTime;

  private:
    void copy(const SM_UserAPP_Finish& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SM_UserAPP_Finish&);

  public:
    SM_UserAPP_Finish(const char *name=nullptr, int kind=0);
    SM_UserAPP_Finish(const SM_UserAPP_Finish& other);
    virtual ~SM_UserAPP_Finish();
    SM_UserAPP_Finish& operator=(const SM_UserAPP_Finish& other);
    virtual SM_UserAPP_Finish *dup() const {return new SM_UserAPP_Finish(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getUserID() const;
    virtual void setUserID(const char * userID);
    virtual const char * getStrVmId() const;
    virtual void setStrVmId(const char * strVmId);
    virtual const char * getStrApp() const;
    virtual void setStrApp(const char * strApp);
    virtual int getNTotalTime() const;
    virtual void setNTotalTime(int nTotalTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SM_UserAPP_Finish& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SM_UserAPP_Finish& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SM_USERAPP_FINISH_M_H

